driver:
  name: vagrant

provisioner:
  name: chef_zero
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: centos-6.7
  - name: centos-7.1

suites:
  - name: default
    run_list:
      - recipe[test::default]
  - name: simple
    run_list:
      - recipe[test::simple]
  - name: read-only
    run_list:
      - recipe[test::read_only]
  - name: networking
    run_list:
      - recipe[test::networking]
  - name: xinetd
    run_list:
      - recipe[test::xinetd]
